services:
  db:
    image: postgres:16
    container_name: futbot-league
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432-5432"
    volumes:
      - postgres_data:/var/lib/postgressql/data

# Adminer to view the database
  admin:
    image: adminer
    restart: always
    depends_on:
      - db
    ports:
    # access Adminer on http://localhost:8080 
      - "8080:8080"
    

volumes:
  postgres_data:

    